services:
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - app_network

  fastapi:
    build:
      context: ./fastapi
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./fastapi:/app
    environment:
      - WATCHFILES_FORCE_POLLING=true  # Helps with file watching in Docker
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - ollama
    networks:
      - app_network

  streamlit:
    build:
      context: ./streamlit
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ./streamlit:/app
    command: streamlit run app.py --server.address 0.0.0.0 --server.runOnSave true
    depends_on:
      - fastapi
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  ollama_data: